image:
  file: .gitpod.Dockerfile

# Git aliases and project-wide configuration.
# Save author and email as environmental variables in your gitpod profile.
gitConfig:
  alias.st: status
  alias.co: checkout
  alias.ci: commit
  alias.br: branch

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
- port: 8888
  onOpen: ignore
- port: 3306
  onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals.
# See https://www.gitpod.io/docs/config-start-tasks/
tasks:
- init: composer install && ln -s ~/bin/adminer.php web/adminer.php
  command: mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED by 'pass';" && mysql -e "GRANT ALL PRIVILEGES ON *.* to 'user'@'localhost';" && mysql -e "CREATE DATABASE db;" && mysql -e "FLUSH PRIVILEGES;" && drush si -y --db-url=mysql://user:pass@localhost:3306/db && drush rs 0.0.0.0:8888
  name: Server
- command: echo "Welcome, please allow Server terminal to finish composer and drupal install. It takes a while!" && gp await-port 8888 && drush uli --uri=$(gp url 8888)
  name: Terminal

vscode:
  extensions:
    - neilbrayfield.php-docblocker@2.1.0:DG/0jImoYat50A1oQ633dQ==
    - mblode.twig-language-2@0.9.1:RU6BsxXlTQVjCzHru+HmBw==
